# Generated by Django 3.2.15 on 2024-09-02 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webpush', '0005_auto_20230614_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='pushinformation',
            options={'ordering': ['user', 'group'], 'verbose_name': 'Push Information', 'verbose_name_plural': 'Push Information'},
        ),
        migrations.AlterModelOptions(
            name='subscriptioninfo',
            options={'ordering': ['browser'], 'verbose_name': 'Subscription Info', 'verbose_name_plural': 'Subscription Infos'},
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pushinformation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webpush_info', to='webpush.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='pushinformation',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webpush_info', to='webpush.subscriptioninfo', verbose_name='Subscription'),
        ),
        migrations.AlterField(
            model_name='pushinformation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webpush_info', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='subscriptioninfo',
            name='auth',
            field=models.CharField(max_length=100, verbose_name='Auth'),
        ),
        migrations.AlterField(
            model_name='subscriptioninfo',
            name='browser',
            field=models.CharField(max_length=100, verbose_name='Browser'),
        ),
        migrations.AlterField(
            model_name='subscriptioninfo',
            name='endpoint',
            field=models.URLField(max_length=500, verbose_name='Endpoint'),
        ),
        migrations.AlterField(
            model_name='subscriptioninfo',
            name='p256dh',
            field=models.CharField(max_length=100, verbose_name='P256DH'),
        ),
        migrations.AlterField(
            model_name='subscriptioninfo',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, verbose_name='User Agent'),
        ),
    ]
