# Generated by Django 5.1.1 on 2024-09-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpush', '0005_auto_20230614_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninfo',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
